### ISSUE TITLE
why you delete steam guide?

### ISSUE THREAD

**Issue by DJshelfmushroom** [zacstarfire/bitburner#2]

**Comment by zacstarfire** [comment]
I am sorry, I am currently at war with Steam, so all my guides are now
private, but they do still exist.
I am currently in the process of creating a new platform for Game Guides
not under control of Steam.

Go to my profile, read my information and add me as a friend.
After I've made sure everything is secure, I can give you access again.

Zac (The Void)

**Comment by DJshelfmushroom** [comment]
Oh. Why do you think steam is bad?

**Comment by zacstarfire** [comment]
Because they lock you into their collective, pollute your mind with THIER
garbage and force you to buy their garbage.
You don't really OWN your games on Steam, you just LEASE them while you pay
the same prices other places where you actually do own the games you
purchase from them.
And they try to hold the threat of removing your access to the games you
purchased if you disobey them.

**Comment by zacstarfire** [comment]
Bitburner Guides are now back online.

**Comment by zacstarfire** [comment]
Welcome Back :)

**Comment by DJshelfmushroom** [comment]
You too! Why'd you bring them back though?

**Comment by zacstarfire** [comment]
I will still support Bitburner and other STEM games on Steam until I can bring a new Gaming Site Online to support STEM Games.
